export { default as NetworkLoggerScreen } from './NetworkLogger/NetworkLoggerScreen';
export { default as MainScreen } from './MainScreen/MainScreen';
export { default as NewsDetailScreen } from './NewsDetail/NewsDetailScreen';
export { default as ForceUpdateScreen } from './ForceUpdate/ForceUpdateScreen';
export { default as SettingScreen } from './Setting/SettingScreen';
export { default as LoginScreen } from './Login/LoginScreen';
export { default as SignUp } from './SignUp/SignUp';
export { default as UploadId } from './UploadID/UploadIDScreen';
export { default as ForgotPassword } from './ForgotPassword/ForgotPassword';
export { default as VerificationCode } from './VeificationCode/VerificationCode';
export { default as ResetPassword } from './ResetPassword/ResetPassword';
export { default as SelfiScreen } from './SelfiScreen/SelfiScreen'
export { default as UploadDocuments } from './UploadDocuments/UploadDocuments';
export { default as Home } from './Home/Home';
export { default as Message } from './Message/Message';
export { default as Profile } from './Profile/Profile';
export { default as AccountSetting } from './AccountSetting/AccountingSetting';
export { default as Address } from './Address/Address';
export { default as Wallet } from './Wallet/Wallet';
export { default as ShareProfile } from './ShareProfile/ShareProfile'
export { default as Notification } from './Notification/Notification';
export { default as HelpAndSupport } from './HelpAndSupport/HelpAndSupport'
export { default as TaskList } from './TaskList/TaskList';
export { default as AddTaskScreen } from './AddTasks/AddTasks';
export { default as CompleteTasks } from './CompleteTasks/CompleteTasks'
export { default as PatientDetail } from './patientDetail/patientDetail'
export { default as PatientSetLocationScreen } from './PatientSetLocation/PatientSetLocationScreen';
export { default as PatientLocationSetupScreen } from './PatientLocationSetup/PatientLocationSetupScreen';
export { default as PatientHomeScreen } from './PatientHome/PatientHomeScreen';
export { default as ChatsScreen } from './Chats/ChatsScreen';
export { default as SingleChatScreen } from './SingleChat/SingleChatScreen';
export { default as HospitalsScreen } from './Hospitals/HospitalsScreen';
export { default as PatientProfileScreen } from './PatientProfile/PatientProfileScreen';
export { default as PatientAccountSettingsScreen } from './PatientAccountSettings/PatientAccountSettingsScreen';
export { default as UploadIDScreen } from './UploadID/UploadIDScreen';
export { default as MedicalHistoryScreen } from './MedicalHistory/MedicalHistoryScreen';
export { default as PatientCreditCardsScreen } from './PatientCreditCards/PatientCreditCardsScreen';
export { default as FavoriteHospitalsScreen } from './favoriteHospitals/favorite-hospitals';

