import { color } from '@src/utils';
import { StyleSheet, Platform } from 'react-native';

const mainStyle = StyleSheet.create({
 modalMainView: {
  flex: 1,
  backgroundColor: color.dark.backgroundColor,
  justifyContent: 'flex-end',
  margin: 0,
 },
 modalTopView: {
  flexDirection: 'row',
  width: '94%',
  alignSelf: 'center',
  alignItems: 'center',
  justifyContent: 'space-between',
  marginBottom: 14,
 },
 modalSubContainer: {
  flex: Platform.OS == 'ios' ? 0.92 : 0.98,
  backgroundColor: '#ffffff',
  paddingHorizontal: 20,
  paddingTop: 20,
 },
 homeTopView: {
  height: '8%',
  backgroundColor: color.dark.backgroundColor,
  flexDirection: 'row',
  alignItems: 'center',
  justifyContent: 'space-between',
  paddingHorizontal: 20,
  elevation: 5,
  shadowColor: '#000000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
  marginBottom: 5,
 },

 homeTabText: {
  color: '#000000',
  fontFamily: Platform.OS == 'ios' ? 'GEDinarOne-Medium' : 'Montserrat-Medium',
  fontSize: 14
 },
 textField: {
  color: '#000000',
  fontFamily: Platform.OS == 'ios' ? 'GEDinarOne-Bold' : 'Montserrat-SemiBold',
  fontSize: 16,
 },
 subText: {
  color: '#000000',
  fontFamily: Platform.OS == 'ios' ? 'GEDinarOne-Medium' : 'Montserrat-Medium',
  fontSize: 14,
 },
 textView: {
  width: '99%',
  marginTop: 10,
  flexDirection: 'row',
  alignSelf: 'center',
  borderRadius: 16,
  backgroundColor: '#ccc',
  paddingHorizontal: 10,
  height: 52,
 },
 inputText: {
  fontFamily: Platform.OS == 'ios' ? 'GEDinarOne-Medium' : 'Montserrat-Medium',
  fontSize: 14,
  color: '#000000',
  width: '100%',
 },
 errorText: {
  color: 'red',
  fontFamily: Platform.OS == 'ios' ? 'GEDinarOne-Medium' : 'Montserrat-Medium',
  fontSize: 12,
  marginTop: 4
 },
 mainView: {
  flex: 1,
  backgroundColor: '#ffffff',
  margin: 0,
  height: '100%',
 },
 headerView: {
  flexDirection: 'row',
  width: '100%',
  alignSelf: 'center',
  paddingVertical: 10,
 },
 subView: {
  flex: 1,
  paddingHorizontal: 20,
 },
 text: {
  color: '#000000',
  textAlign: 'left',
  fontWeight: 'bold',
  fontFamily: Platform.OS == 'ios' ? 'GEDinarOne-Medium' : 'Montserrat-Medium',
  fontSize: 16,
  marginBottom: 16,
 },
 inputFieldView: {
  marginBottom: 16,
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
 },
 button: {
  justifyContent: 'center',
  alignSelf: 'center',
  paddingTop: 15,
  paddingBottom: Platform.OS == 'ios' ? 15 : 10,
  backgroundColor: '#ffffff',
  width: '100%',
  position: 'absolute',
  bottom: 0,
 },
 headerText: {
  // textAlign: 'center',
  width: '100%',
  color: '#ffffff',
  fontFamily: Platform.OS == 'ios' ? 'GEDinarOne-Bold' : 'Montserrat-Bold',
  fontSize: 22,
  // paddingVertical: 20

 },
 progressBar: {
  width: '50%',
  alignSelf: 'center',
  flexDirection: 'row',
  marginVertical: 10,
  justifyContent: 'space-between',
  alignItems: 'center',
 },
 progressStyle: {
  height: 60,
  resizeMode: 'contain',
  alignSelf: 'center',
 },
 footerBtn: {
  height: 52,
  width: '100%',
  backgroundColor: color.dark.backgroundColor,
  alignItems: 'center',
  alignSelf: 'center',
  marginBottom: 16,
  marginVertical: 40,
  borderRadius: 16,
  justifyContent: 'center',

 },
 signBtn: {
  height: 52,
  width: '70%',
  borderRadius: 10,
  backgroundColor: color.dark.backgroundColor,
  alignItems: 'center',
  alignSelf: 'center',
  marginBottom: 16,
  justifyContent: 'center',

 },
 footerBtnTxt: {
  color: '#ffffff',
  fontFamily: 'Montserrat-SemiBold',
  fontSize: 16,
  textAlign: 'center',
 },
 declineBtn: {

  justifyContent: 'center',
  height: 52,
  width: '70%',
  backgroundColor: '#ffffff',
  alignItems: 'center',
  alignSelf: 'center',
  marginBottom: 16,
  borderTopRightRadius: 16,
  borderBottomLeftRadius: 16,
  borderWidth: 1,
  borderColor: color.dark.backgroundColor
 },
 declineBtnText: {
  color: color.dark.backgroundColor,
  fontFamily: 'Montserrat-SemiBold',
  fontSize: 16,
  textAlign: 'center',
 },
 appLogo: {
  height: 50,
  width: 100,
  alignSelf: 'center',
  marginTop: 20,
 },
 mainConatainer: {
  paddingHorizontal: 20,
 },
 title: {
  marginTop: 10,
 },
 splashText: {
  color: '#ffffff',
  alignSelf: 'center',
  fontFamily: Platform.OS == 'ios' ? 'GEDinarOne-Medium' : 'Montserrat-Medium',
  fontSize: 18,
  marginTop: 100,
 },
 splashBtn: {
  backgroundColor: color.dark.backgroundColor,
  alignItems: 'center',
  borderRadius: 10,
  borderColor: '#ffffff',
  borderWidth: 1,
  alignSelf: 'flex-end',
  justifyContent: 'center',
  shadowRadius: 2,
  height: 40,
  width: 56,
 },
 splashView: {
  flex: 0.4,
  justifyContent: 'space-between',
  padding: 20,
  elevation: 5,
  shadowColor: '#000000',
  shadowOffset: { width: 0, height: 1 },
  shadowOpacity: 0.1,
  shadowRadius: 2,
 },
 listView: {
  flexDirection: 'row',
  borderBottomColor: '#000000',
  borderBottomWidth: 0.2,
  justifyContent: 'space-between',
  alignItems: 'center',
  paddingVertical: 10,
  width: '80%'
 },
 eligibilityList: {
  padding: 14,
  justifyContent: 'center',
  width: '100%',
  borderRadius: 10,
  backgroundColor: '#ccc',
  marginTop: 20
 },
 loadingIndicator: {
  position: 'absolute',
  left: 120,
  top: 300,
  alignItems: 'center',
  justifyContent: 'center',
  backgroundColor: '#ccc',
  height: '15%',
  width: '30%',
  borderRadius: 30,
  alignSelf: 'center'
 },
 modalContainer: {
  backgroundColor: 'rgba(238, 238, 237, 0.70)',
  position: 'absolute',
  flex: 1,
  alignItems: 'center',
  justifyContent: 'center',
  flexDirection: 'row'
 },
 ModalContainer: {
  width: '90%',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
  textAlign: 'center',
  color: '#fff',
  paddingHorizontal: 15,
  paddingVertical: 20,
  borderRadius: 20,
  elevation: 1,
  borderColor: '#E8E8E8',
  borderWidth: 1,
  shadowColor: '#000',
  shadowOffset: { height: 2, width: 0 },
  shadowOpacity: 0.25,
  backgroundColor: 'white'
 },
 SignUptext: {
  fontFamily: Platform.OS == 'ios' ? 'GEDinarOne-Bold' : 'Montserrat-SemiBold',
  fontSize: 12,
  color: color.dark.backgroundColor,
 },
})
export default mainStyle;
